version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - "C:/Users/Ian Murimi/Desktop/Pr/Python/Projects/VoucherMS/VoucherMS/media:/media"
    build:
     context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - "C:/Users/Ian Murimi/Desktop/Pr/Python/Projects/VoucherMS/VoucherMS/media:/media"
      - ./nginx-logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
 static:
 media:
      